<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<script type="text/javascript">var webRootPath = "";</script>
<title>产品生产流程合作视图-合作范围  </title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="../css/co.css" >
<div class="content content-tab" id="requisition_info">
	<div class="panel-tab">
				<form id="advice_form"  name="advice_form" action="http://127.0.0.1:8020/10000/action/action/action_area_1.action" method="post">
					<p class="copy1">细分市场维度的合作视图 </p>
								<p class="copy3">合作范围并非一成不变，中国电信四川公司期待与您共同开拓新的合作领域！  </p>
								<table class="table table-orange">
									<colgroup>
										<col class="span1" />
										<col class="span1" />
										<col class="span1" />
										<col class="span1" />
										<col class="span1" />
									</colgroup>
									<thead>
										<th></th>
										<th>专业市场</th>
										<th>大中企业</th>
										<th>住宅小区</th>
										<th>个人市场</th>
									</thead>
									<tbody>
										<tr>
											<td>产品开发</td>
											<td>√</td>
											<td>√</td>
											<td>√</td>
											<td>——</td>
										</tr>
										<tr>
											<td>系统平台建设</td>
											<td>——</td>
											<td>——</td>
											<td>——</td>
											<td>——</td>
										</tr>
										<tr>
											<td>网络支撑</td>
											<td>——</td>
											<td>——</td>
											<td>√</td>
											<td>——</td>
										</tr>
										<tr>
											<td>终端提供</td>
											<td>√</td>
											<td>√</td>
											<td>√</td>
											<td>——</td>
										</tr>
										<tr>
											<td>渠道代理</td>
											<td>√</td>
											<td>√</td>
											<td>√</td>
											<td>√</td>
										</tr>
										<tr>
											<td>内容运营</td>
											<td>——</td>
											<td>——</td>
											<td>——</td>
											<td>√</td>
										</tr>
										<tr>
											<td>服务支撑</td>
											<td>——</td>
											<td>——</td>
											<td>——</td>
											<td>——</td>
										</tr>
									</tbody>
								</table>
				</form>
	</div>
</div>