<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<script type="text/javascript">var webRootPath = "";</script>
<title>政企类合作伙伴引入基本信息-合作伙伴条件  </title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="../css/co.css" >
<div class="content-tab" id="requisition_info">
	<div class="panel-tab">
		<form id="advice_form"  name="advice_form" action="http://127.0.0.1:8020/10000/action/action_condition_0.action" method="post">
			<table class="table table-orange">
									<thead>
										<tr style="mso-yfti-irow:0;">
											<td colspan="2" rowspan="2">合作伙伴</td>
											<td colspan="2">合作拓展型</td>
											<td>合作运营型</td>
										</tr>
											<tr style="mso-yfti-irow:1;">
											<td>合作直销队</td>
											<td>关系型合作伙伴</td>
											<td>行业应用合作伙伴 </td>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td colspan="2">选择原则 </td>
											<td>销售能力
											<br />
											客户资源
											<br />
											忠诚度
											<br />
											</td>
											<td> 客户资源
											<br />
											渠道资源 </td>
											<td>
											<br />
											服务能力
											<br />
											资金平台 </td>
										</tr>
										<tr style="mso-yfti-irow:3;">
											<td rowspan="3">法律层面 </td>
											<td>企业法人营业执照 </td>
											<td>√</td>
											<td>√</td>
											<td>√</td>
										</tr>
										<tr style="mso-yfti-irow:4;">
											<td>资质证明 </td>
											<td>√</td>
											<td>√</td>
											<td>√</td>
										</tr>
										<tr style="mso-yfti-irow:5;">
											<td>税务登记证</td>
											<td>√</td>
											<td>√</td>
											<td>√</td>
										</tr>
										<tr style="mso-yfti-irow:6;">
											<td rowspan="4">市场层面</td>
											<td>商业计划书</td>
											<td><span style="mso-fareast-language:KO">
												<o:p>
													&nbsp;
												</o:p> </td>
											<td> √ </td>
											<td > √ </td>
										</tr>
										<tr style="mso-yfti-irow:8">
											<td > 保证金额 </td>
											<td> √ </td>
											<td> √ </td>
											<td > √ </td>
										</tr>
										<tr style="mso-yfti-irow:8">
											<td > 排他要求 </td>
											<td> √ </td>
											<td><span style="mso-fareast-language:KO">
													<o:p>
													&nbsp;
												</o:p> </td>
											<td > √ </td>
										</tr>
										<tr style="mso-yfti-irow:9">
											<td> 终端品牌代理授权 </td>
											<td> √ </td>
											<td> √ </td>
											<td> √ </td>
										</tr>
										<tr style="mso-yfti-irow:10">
											<td  rowspan="5"> 其他层面 </td>
											<td > 资金实力 </td>
											<td>5 万元 </td>
											<td> √ </td>
											<td > √ </td>
										</tr>											
										<tr>
										<td>企业规模</td>
											<td>
											<o:p>
												&nbsp;
											</o:p></td>
											<td>
											<o:p>
												&nbsp;
											</o:p></td>
											<td > √ </td>
										</tr>
										<tr>
											<td > 信誉资质 </td>
											<td> √ </td>
											<td> √ </td>
											<td > √ </td>
										</tr>
										<tr>
											<td> 服务要求 </td>
											<td> √ </td>
											<td> √ </td>
											<td > √ </td>
										</tr>
										<tr>
											<td > 团队素质 </td>
											<td> √ </td>
											<td> √ </td>
											<td > √ </td>
										</tr>
									</tbody>
								</table>
		</form>
	</div>
</div>