<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
	<script type="text/javascript">var webRootPath = "";</script>
	<title>产品生产流程合作视图-合作范围  </title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" type="text/css" href="../css/co.css" >
	<div class="content-tab" id="requisition_info">
		<div class="panel-tab">
			<form id="advice_form"  name="advice_form" action="http://127.0.0.1:8020/10000/action/action/action_support_1.action" method="post">
				<p class="copy1">产品生产流程合作视图 </p>
				<p class="copy2"><img src="../img/square_dot.gif" /> 基础接入产品 </p>
				<p class="copy3"> －产品开发、系统平台建设、核心网络等领域以电信公司为主。</p>
				<p class="copy3">－接入网支撑建设积极寻求合作。</p>
				<p class="copy3">－终端、渠道、内容运营和服务支撑等领域均主要通过合作发展。 </p>
				<table class="table table-orange">
					<colgroup>
						<col class="span2" />
						<col class="span2" />
						<col class="span2" />
						<col class="span2" />
					</colgroup>
					<thead>
						<th></th>
						<th>A 宽带 </th>
						<th>B 移动 </th>
						<th>C 固话 </th>
					</thead>
					<tbody>
						<tr>
							<td>产品开发</td>
							<td>——</td>
							<td>——</td>
							<td>——</td>
						</tr>
						<tr>
							<td>系统平台建设 </td>
							<td>——</td>
							<td>——</td>
							<td>——</td>
						</tr>
						<tr>
							<td>网络支撑 </td>
							<td>√</td>
							<td>√</td>
							<td>√</td>
						</tr>
						<tr>
							<td>终端提供 </td>
							<td>√</td>
							<td>√</td>
							<td>√</td>
						</tr>
						<tr>
							<td>渠道代理 </td>
							<td>√</td>
							<td>√</td>
							<td>√</td>
						</tr>
						<tr>
							<td>内容运营 </td>
											<td>——</td>
											<td>SP、CP</td>
											<td>SP、CP</td>
										</tr>
										<tr>
											<td>服务支撑 </td>
											<td>宽心服务、装维服务</td>
											<td>终端维修</td>
											<td>装维服务、终端维修</td>
										</tr>
									</tbody>
								</table>
								<p class="copy2"><img src="../img/square_dot.gif" />应用产品 </p>
								<p class="copy3"> － 核心网络支撑领域以电信公司为主。</p>
								<p class="copy3">－ 除网络以外，应用产品价值链上的所有环节均全方位对合作伙伴开放、并依靠合作伙伴发展电信负责为您提供标准接口。 </p>
								<table class="table table-orange">
									<colgroup>
										<col class="span2" />
										<col class="span3" />
										<col class="span3" />
									</colgroup>
									<thead>
										<th></th>
										<th>标准应用产品</th>
										<th>行业信息化</th>
									</thead>
									<tbody>
										<tr>
											<td>产品开发</td>
											<td> 1、基于基础接入的标准应用产品
												 2、基于增值业务标准接口进行二次开发的标准应用产品
												 3、新技术新应用探索孵化   
											</td>
											<td>
												 1、基于基础产品为载体的行业应用
												 2、不需电信基础产品承载的客户综合信息化平台ICT建设合作
											</td>
										</tr>
										<tr>
											<td>系统平台建设</td>
											<td>应用产品系统部署所需通用硬件设备及专用硬件设备</td>
											<td>客户应用层系统平台建设</td>
										</tr>
										<tr>
											<td>网络支撑</td>
											<td>——</td>
											<td>校园LAN、客户内部网络</td>
										</tr>
										<tr>
											<td>终端提供</td>
											<td>应用类产品专用终端</td>
											<td>定制终端</td>
										</tr>
										<tr>
											<td>渠道代理</td>
											<td>应用类产品专用终端</td>
											<td>SI </td>
										</tr>
										<tr>
											<td>内容运营</td>
											<td> 
												1、由合作方提供应用产品运营所需的资质版权内容。包括视频、网站、音频、彩信、短信等
												2、由合作方负责对应用产品的内容进行日常运营、维护。
											</td>
											<td>SA </td>
										</tr>
										<tr>
											<td> 服务支撑 </td>
											<td>标准应用产品合作方在进行开发、建设、渠道、内容等方面合作时，直接负责承担服务支撑</td>
											<td>配套行业应用产品、渠道的服务支撑</td>
										</tr>
									</tbody>
								</table>
				</form>
	</div>
</div>