<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<script type="text/javascript">var webRootPath = "";</script>
<title>公众类合作伙伴引入基本信息-合作伙伴条件 </title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="../css/co.css" >
<div class="content-tab" id="requisition_info">
	<div class="panel-tab">
		<form id="advice_form"  name="advice_form" action="http://127.0.0.1:8020/10000/action/action_condition_1.action" method="post">
			<table class="table table-orange">
				<img src="../img/hzlx.jpg" />
			</table>	
		</form>
	</div>
</div>